### ISSUE TITLE
New Ampere.StoragePro E3

### ISSUE THREAD

**Issue by dboeni** [dboeni/home-assistant-ampere-storage-pro-modbus#4]
Hello Ampere.StoragePro E3,

There will be a new Ampere.StoragePro with the designation E5 from September 2024.

To ensure that this integration can also work with this inverter, I need support.

Please contact me

Info Link: [Ampere.StoragePro E3](https://amperesolar.de/storagepro)

**Comment by Isungur** [comment]
I am new to Home Assistant so i might not be the one to help putting things together.
But i have an Ampere.StoragePro E3. If this helps just tell me.

**Comment by dboeni** [comment]
Okay, but maybe one or the other will help us.

Questions:
- Do you have the Ampere.IQ box?
- Can you see the inverter in the network?
- How long have you been using Home Assistant (experience)?
  - Experience with NodeRed?
  - Experience with Visual Studio Code?

I would be delighted if we could perhaps find out something

**Comment by Isungur** [comment]
I have an Ampere.IQ box.
I can see the inverter in my network. At least i am pretty sure its the inverter.
I am completely new to Home Assistant. Just started setting it up and importing stuff about a week ago. I got no experience with NodeRed and little to no experience with Visual Basic.
I did it stuff as my job for a long time so there is basic knowledge for the most things.
I am open for a discord session if this helps. 😊

**Comment by UDicke** [comment]
Very good! It would be nice to find out the relevant modbus registers for enableling dboeni to make his integration running with the new Ampere.StoragePro E3 as well as implementing this in evcc, which is a brilliant tool for surplus charging.
I do not have the ampere.IQ.box and I am happy with managing everything with home assistant and evcc (installed as HA Add on)



> I can see the inverter in my network. At least i am pretty sure its the inverter.
> I am completely new to Home Assistant. Just started setting it up and importing stuff about a week ago. I got no experience with NodeRed and little to no experience with Visual Basic.
> I did IT stuff as my job for a long time so there is basic knowledge for the most things.

That was exactly my situation about one year ago, having an installed Ampere.Storage.Pro, some additional inverters in our site, an existing wallbox and no support from EDK-Solar. So I decided to look for a solution by myself, instead waiting for the fulfilment of EKD-Solar promises and I am very happy with this now (as said already)!!

Since I hopefully have reliable information that the manufacturer of the new E3 is also "SAJ", I would recommend just starting with a small toolbox before you open the big toolbox together with dboeni.

download qmodbusmaster: https://sourceforge.net/projects/qmodmaster/ 
this has to be unpacked and not installed.
then you try to connect to your inverter. Use Options>Modbus TCP and fill in the IP of your inverter

![Image](https://github.com/user-attachments/assets/ee7a1803-dfdb-42ff-b6e6-1dee12ea9425)

Then you connect using the marked button. On the left side downwards the LED should change from red to green.

![Image](https://github.com/user-attachments/assets/2c02c6ed-3e67-4d1f-9b1f-edd82ed0af77)

Under View>Tools you might "ping" and check the Port Status of 502. Report slave ID is not for TCP Connection as far as I know.

Then you might check some register, hopefully they are the same as  for the E2 model...
Here is a SAJ modbus doc that lists register for 4 MPPT. Just give it a try....


[H2-3~6K-S2 single phase communication protocol -2022.12.02-EN.pdf](https://github.com/user-attachments/files/18947636/H2-3.6K-S2.single.phase.communication.protocol.-2022.12.02-EN.pdf)

Here is an example from my site for register 408D (Hex) Phase R Voltage = 234,4 V

![Image](https://github.com/user-attachments/assets/dacfd92e-aa12-45d5-b7ed-4920a1ae686d)

Good luck!

**Comment by dboeni** [comment]
Thank you for your support, @UDicke.
Unfortunately, it is not a "saj" inverter. The manufacturer is a FoxESS.

@Isungur
We can have a look at it together and talk on the phone. How can I write to you on discord?

**Comment by Isungur** [comment]
You should find me at my nick as it is on github. (isungur)

**Comment by UDicke** [comment]
> Unfortunately, it is not a "saj" inverter. The manufacturer is a FoxESS.

Are you sure? I have the information that it is still SAJ, but I am not sure whether this is true.
When I see the history, that seems plausible. 
- SAJ with Ampere label
- SAJ with Ampere label and in black now
- own new design with another provider?

**Comment by dboeni** [comment]
Correct. The white and black inverters are from SAJ.

The new Prosche design is from a different manufacturer. I got this information directly from the ampere software.
FoxESS Hybrid with Modbus (Port 502)

**Comment by UDicke** [comment]
Thank you for this, I wish you success while finding out the necessary informations to support this unit!
If I can help somehow, please let me know. 😊

**Comment by UDicke** [comment]
If it is really a FoxESS this might help or simply work...
https://github.com/nathanmarlor/foxess_modbus
I think it's worth a try

Maybe this repository was already known, but I'm reporting it anyway.

**Comment by Isungur** [comment]
I tried this one but i got an error: "Error connecting to your inverter. Details: Inverter model not supported: 'ASP-12KW-3P-A-E3'

**Comment by bierma1966** [comment]
@dboeni 
That is the datasheet what i have found 2 weeks ago in the USA and UK.

[EN-PowerQube(UK)-datasheet-V2.0-20241129.pdf](https://github.com/user-attachments/files/18970253/EN-PowerQube.UK.-datasheet-V2.0-20241129.pdf)

**Comment by dboeni** [comment]
I read sunspech(Modbus), very interesting

**Comment by UDicke** [comment]
I just took a look to the datasheet of Ampere.StoragePro E3 and found:
"Integrierter Hybrid-Wechselrichter 3-phasig mit bis zu 12 kW, **3 unabhängige MPPT** & Verschattungsmanagement"
before that I thought this model has 4 MPPT because of this:

![Image](https://github.com/user-attachments/assets/d4806b86-d6bf-4f05-8538-254c0fae5ef7)

This lets me believe now that "FoxESS" may be true...

**Comment by Limmbo** [comment]
I just received my Ampere.StoragePro E3 with the IQ Box. Are there any updates on this topic? I would like to add it to my Home Assistant.

**Comment by Limmbo** [comment]
@dboeni I am an software tester, so at least I know a bit about programming in general. I am quite new to homeassistant and all that yaml stuff (like but I am eager to learn it). So if you (and MadMan) have something what I could test I will try it.

**Comment by joachimgr68** [comment]
Ampere.StoragePro E3 with "Porsche-design" from EKD

**Comment by Isungur** [comment]
As far as i know there is no integration by now.
We are sure it is a FoxESS. If you use the REST of the IP-Box you get some parameters that show it is a FoxESS.
I integrated some sensors via REST/TCP. At least i can see some parameters by now even if i am not sure if everyone is the right parameter.
Below what i wrote into my configurations.yaml (X-ed the IP-adress of my IQ-Box and *-ed the serial of my inverter)
```
sensor:
#Total battery Discharge in kwh

- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_battery_AS12AE3********_battery_work_out_total
  name: PV_Batterie Entladung in kWh
  value_template: '{{ value_json.state | regex_replace("([^\d.-]+)","") | float }}'
  unit_of_measurement: "kWh"
  device_class: energy
  state_class: total_increasing
  scan_interval: 15

#Total battery Charge in kWh

- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_battery_AS12AE3********_battery_work_in_total
  name: PV_Batterie Ladung in kWh
  value_template: '{{ value_json.state | regex_replace("([^\d.-]+)","") | float }}'
  unit_of_measurement: "kWh"
  device_class: energy
  state_class: total_increasing
  scan_interval: 15

#Total Battery Dis-/Charge in kwh

- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_battery_AS12AE3********_battery_bms_power
  name: PV_Batterie Ent-/Ladung in W
  value_template: '{{ value_json.state | regex_replace("([^\d.-]+)","") | float }}'
  unit_of_measurement: "W"
  device_class: energy
  state_class: total_increasing
  scan_interval: 15

#Battery charge/Discharge in W with negatives inverted for right Dashboard functionality

- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_battery_AS12AE3********_battery_bms_power
  name: PV_Aktueller Batterie Ladezustand in W
  value_template: "{{ '%0.2f'|format((value_json.state.split(' ')[0] | float) * -1) }}"
  unit_of_measurement: "W"
  device_class: energy
  state_class: measurement
  scan_interval: 15

#Powermeterhouse in W
- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_meter_AS12AE3********_metering_getConsumption_P_active
  name: PV_Aktuelle Leistung aus dem Netz
  value_template: '{{ value_json.state | regex_replace("([^\d.]+)","") | float }}'
  unit_of_measurement: "W"
  device_class: energy
  state_class: measurement
  scan_interval: 15

#Solar power in W

- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_inverter_AS12AE3********_limitable_getActualProductionPower_P_active
  name: PV_Aktuelle Leistung von den Solarpanelen
  value_template: '{{ value_json.state | regex_replace("([^\d.]+)","") | float }}'
  unit_of_measurement: "W"
  device_class: energy
  state_class: measurement
  scan_interval: 15

#State Of Charge Battery in %
- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_battery_AS12AE3********_battery_bms_soc
  name: PV_Ladestatus der Batterie
  value_template: "{{ '%0.2f'|format(value_json.state.split(' ')[0] | float) }}"
  unit_of_measurement: "%"
  device_class: energy
  state_class: measurement
  scan_interval: 15

#Total Engergy out of the inverter I use this as total Solar Power produced but I'm not shure if this also includes energy out of the Battery
- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_inverter_AS12AE3********_inverter_work_pv_total
  name: PV_solar_total_inverter_energyOut
  value_template: '{{ value_json.state | regex_replace("([^\d.-]+)","") | float }}'
  unit_of_measurement: "kWh"
  device_class: energy
  state_class: total_increasing
  scan_interval: 15

#Powermeter Export
- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_meter_AS12AE3********_meter_work_out_total
  name: PV_Einspeisung ins Netz
  value_template: '{{ value_json.state | regex_replace("([^\d.-]+)","") | float }}'
  unit_of_measurement: "kWh"
  device_class: energy
  state_class: total_increasing
  scan_interval: 15

#Powermeter Export
- platform: rest
  resource: http://192.168.XXX.XXX/rest/items/foxesshybrid_meter_AS12AE3********_meter_work_in_total
  name: PV_Aus dem Netz
  value_template: '{{ value_json.state | regex_replace("([^\d.-]+)","") | float }}'
  unit_of_measurement: "kWh"
  device_class: energy
  state_class: total_increasing
```

**Comment by tommyguuuun** [comment]
I also have the E3 "Porsche Design" Modell with an IQ Box. I'm really looking forward to that integration, if i can help with anything, just let me know.

**Comment by Limmbo** [comment]
Thank you @Isungur , I just adapted your code and it is working.

**Comment by rusor1977** [comment]
> Hallo Ampere.StoragePro E3
> 
> Ab September 2024 wird es einen neuen Ampere.StoragePro mit der Bezeichnung E5 geben.
> 
> Damit diese Integration auch mit diesem Wechselrichter funktionieren kann, brauche ich Unterstützung.
> 
> Bitte kontaktieren Sie mich
> 
> Info-Link: [Ampere.StoragePro E3](https://amperesolar.de/storagepro)

ja ich habe Ampere Storage Pro E3: 
INVERTER-AS22AE3051CJ077
SP-ASPAE3-22-9.9

brauche Hilfe bei Integration

können Sie mir helfen?

**Comment by joachimgr68** [comment]
Hello again - I think answer is "no" for EKD devices with Porsche design.
Seems all ports (except the rest api interface) are blocked.
So only way (also I did it) is to get information via REST Api interface (see comments above)

Did anyone already also send a message to EKD system to control the system or all only using the "get" funktion to receive data from system?

**Comment by joachimgr68** [comment]
Hallo - auf Deutsch, da die Übersetzung oben so keinen Sinn macht :-)
@rusor1977:
siehe Beschreibung oben von "lsungur"
--> sende per Browser folgende URL:            http://192.168.xxx.xxx/rest/items/
mit "192.168.xxx.xxx" - IP Deiner Anlage (IQ Box)

Als Antwort bekommst Du alle verfügbaren Informationen der Anlage.

In HA benötigst Du die "RESTful" Integration und ein passendes yaml File (Bsp. siehe oben von lsungur).
Das erzeugt dann Entitäten, die Du in HA benutzen/auswerten kannst.

Gruß 
(und viel Glück)

**Comment by joachimgr68** [comment]
I know -  was not my intension :-|
Sad about - because it seems nevertheless a good system (from technical point of view)

**Comment by Sebastianvdm** [comment]
Das habe ich versucht. In meiner Fritz Box wird nur die Ampere iQ als IP angezeigt.  (Über energymanager.local erreichbar). Ich vermute das der Amperstorage und die WallBox irgendwie damit verknüpft ist und deswegen keine eigene IP haben.

**Comment by bierma1966** [comment]
I forgot to mention that the Wallbox has a default IP address in the factory state

![Image](https://github.com/user-attachments/assets/8ae80ca9-b66a-4c24-bd1b-48ca142fb83b)

Can you post a picture of how the devices are connected to the Kiwigrid.

**Comment by Sebastianvdm** [comment]
I think the IP is from the Ampere.iQ (Kiwigrid) not from the Ampere Storage….

**Comment by bierma1966** [comment]
So wie ich deine Skizze verstehe gehen alle Geräte über den Switch zum Router und müssten somit eine IP Adresse haben.
Steck doch einfach mal die IQ Box aus und kontrollier dann mal deine Fritzbox.

**Comment by tommyguuuun** [comment]
> Also die IP der Ampere.iQ Box ist im Router zu sehen. Man kann auf die Weboberfläche zugreifen und einiges einsehen. Die WallBox und derWechselrichter mit Speicher haben keine eigene IP im Router. scheinen irgendwie mit der Ampere.iQ Box verknüpft zu sein.
> 
> <img alt="Image" width="2000" height="944" src="https://private-user-images.githubusercontent.com/175305179/481592899-c126effd-e4db-4aa2-a10a-e6aa5e9d99af.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxMjEzNDQsIm5iZiI6MTc1NjEyMTA0NCwicGF0aCI6Ii8xNzUzMDUxNzkvNDgxNTkyODk5LWMxMjZlZmZkLWU0ZGItNGFhMi1hMTBhLWU2YWE1ZTlkOTlhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNVQxMTI0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDVmMDBkNmZkNTU5Y2I4NDE1OGI4YmI4ZDU1ZDZiMTViZTEwYjdhODc1NmEzNDMyM2RmNWY4NThmMTY4Y2MxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.47PzlazWU3pGe7oDEZbtP28DbODis4_Kbg8pA9Lr3D8"> <img alt="Image" width="2000" height="1344" src="https://private-user-images.githubusercontent.com/175305179/481592900-6d4b5b8d-eca5-4cb7-a1e8-96d3252c39fe.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxMjEzNDQsIm5iZiI6MTc1NjEyMTA0NCwicGF0aCI6Ii8xNzUzMDUxNzkvNDgxNTkyOTAwLTZkNGI1YjhkLWVjYTUtNGNiNy1hMWU4LTk2ZDMyNTJjMzlmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNVQxMTI0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTM5ZWZmNjJlNzJjMDE4MjRkOWRkNWI1ZDRjZTFjZmQ0YzFhYjhiZDI3OTRkM2Y4ZDhhNTQzZDJmZGZlZjUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oy3UHhQHfiNCIX98lQjR2RcIr1W8DwgcAvaTM_2Ih7M">

Kann ich so nicht bestätigen, bei mir hat die StoragePro E3 eine eigene IP und auch ein Webinterface über diese. Jedoch will er dort ein Passwort, welches nicht bekannt ist.

**Comment by Sebastianvdm** [comment]
dachte das wäre mein Switch.....

**Comment by tommyguuuun** [comment]
> meinst du diese Oberfläche?
> 
> <img alt="Image" width="1106" height="633" src="https://private-user-images.githubusercontent.com/175305179/481597910-2ae378f8-fdb5-479d-8430-b59dbd6b4e42.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYxMjE2ODMsIm5iZiI6MTc1NjEyMTM4MywicGF0aCI6Ii8xNzUzMDUxNzkvNDgxNTk3OTEwLTJhZTM3OGY4LWZkYjUtNDc5ZC04NDMwLWI1OWRiZDZiNGU0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNVQxMTI5NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTZkMDY4NzNjNDU5YjQyMDBhNjgxNTA1NmNmOWMxOTc5MDQ4NjViOGQ0ZTkwOTEyYTg3YWUzYzYyNzI3ZjJjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.j8VCw5ctYatMtUNdtbTRDikzkXcjfBpOyY-CxvaM8NI">

Genau! Das ist die Storage.

**Comment by dboeni** [comment]
Hallo zusammen,
hatte die Tage/Wochen viel zu tun.

Ich war schon mit jemanden an auslesen nur läuft die Anlage leider nicht mehr.
Kann es mit jemanden anderen Testen und ausprobieren. Dauert vielleicht etwas länger und paar Tage, bis wir vielleicht zu einem Ergebnis kommen. Wer hat Lust?

**Comment by tommyguuuun** [comment]
Heute ist mir aufgefallen, dass ich keinen Zugriff mehr auf die Rest API über die IP habe für HA… nur nach dem einloggen ist die url aufrufbar

**Comment by joachimgr68** [comment]
> Heute ist mir aufgefallen, dass ich keinen Zugriff mehr auf die Rest API über die IP habe für HA… nur nach dem einloggen ist die url aufrufbar

Gleichfalls .... schein ein "update" zu sein. Wie bist Du weiter vorgegangen?

**Comment by tommyguuuun** [comment]
> > Heute ist mir aufgefallen, dass ich keinen Zugriff mehr auf die Rest API über die IP habe für HA… nur nach dem einloggen ist die url aufrufbar
> 
> Gleichfalls .... schein ein "update" zu sein. Wie bist Du weiter vorgegangen?

Gar nicht… weiß nicht was ich da jetzt machen sollte…

**Comment by joachimgr68** [comment]
> > > Heute ist mir aufgefallen, dass ich keinen Zugriff mehr auf die Rest API über die IP habe für HA… nur nach dem einloggen ist die url aufrufbar
> > 
> > 
> > Gleichfalls .... schein ein "update" zu sein. Wie bist Du weiter vorgegangen?
> 
> Gar nicht… weiß nicht was ich da jetzt machen sollte…

Prinzipiell wäre ja die Herausforderung per HA ein login zu schicken, danach ist ja der Zugriff wieder möglich ....

**Comment by Isungur** [comment]
Das ist mir vor ein paar Tagen auch aufgefallen. Habe bisher versucht via Browser in HA einen Login durchzuführen. Hat leider nichts geändert.

**Comment by tommyguuuun** [comment]
> Hallo zusammen, hatte die Tage/Wochen viel zu tun.
> 
> Ich war schon mit jemanden an auslesen nur läuft die Anlage leider nicht mehr. Kann es mit jemanden anderen Testen und ausprobieren. Dauert vielleicht etwas länger und paar Tage, bis wir vielleicht zu einem Ergebnis kommen. Wer hat Lust?

Wenn du mich anleiten kannst, können wir das gerne zusammen in Angriff nehmen!

**Comment by joachimgr68** [comment]
> Das ist mir vor ein paar Tagen auch aufgefallen. Habe bisher versucht via Browser in HA einen Login durchzuführen. Hat leider nichts geändert.

Kannst Du mir bitte sagen wie Du den login durchgeführt hast? War der login erfolgreich und kam dann auf xxx.xxx.xxx.xx/rest/items im Browser nichts zurück?

**Comment by Isungur** [comment]
Ich habe mir Firefox als Browser in HA installiert und mich dort eingeloggt. Leider wurde das nicht für das gesamte Gerät hinterlegt und entsprechend kamen trotzdem keine Werte über die REST Abfrage.

**Comment by joachimgr68** [comment]
> Ich habe mir Firefox als Browser in HA installiert und mich dort eingeloggt. Leider wurde das nicht für das gesamte Gerät hinterlegt und entsprechend kamen trotzdem keine Werte über die REST Abfrage.

Hi - vielleicht könntest Du mir bitte eine PN schicken auf jgr.homeassistant@gmail.com ?

**Comment by Sebastianvdm** [comment]
Nach ein bisschen Tüftelei ist mein Stand momentan folgender:
* Der Rest-Endpunkt des Energiemanagers liefert nach Authentifizierung im Browser über das Nutzer-UI verwertbares Json:

```json
{
  "link": "http://karaf/rest/items/foxesshybrid_inverter_AS12xxxxxxx_limitable_getActualProductionPower_P_active",
  "state": "3904 W",
  "stateDescription": {
    "pattern": "%.2f %unit%",
    "readOnly": true,
    "options": []
  },
  "editable": true,
  "type": "Number:Power",
  "name": "foxesshybrid_inverter_AS12xxxxxxx_limitable_getActualProductionPower_P_active",
  "label": "#active_power",
  "tags": [
    "emiaas_resolver"
  ],
  "groupNames": []
}
```

* Folgende Konfiguration in den Entwicklerwerkzeugen des HomeAssistant liefert jedoch die Fehlermeldung bzw. eigentlich das Warninng: `'value_json' is undefined`:

```yaml
template:
  - sensor:
      - platform: rest
        resource: http://192.168.xxx.xxx/rest/items/foxesshybrid_inverter_AS12xxxxxxx_limitable_getActualProductionPower_P_active
        username: xxxx
        password: xxxx
        authentication: basic
        value_template: "{{ value_json }}"
```

Zunächst dachte ich, dass das Auslesen des Wertes mit Hilfe der Template-Engine fehlerhaft ist. Inzwischen bin ich überzeugt, dass die Authentifizierung des HomeAssistant beim Energiemanager nicht funktioniert. Fraglich ist, wie HomeAssistant sich als Rest-Client beim Energiemanager anmeldet. Am liebsten wäre mir eine token-basierte Authentifizierung, da ich das Passwort des Eneregiemanagers leider nicht ändern kann.
